Remove API condition of turn off button #686
lablup/backend.ai-console pull request #705
Opened 2020-09-10 08:29 UTC by seeun-320

2020-09-10 08:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lablup/backend.ai-console?pullRequest=705) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/lablup/backend.ai-console?pullRequest=705) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lablup/backend.ai-console?pullRequest=705) it.</sub>

2020-09-11 00:13 UTC, adrysn requested changes
Good to remove support for legacy API (<5). I want to display the destroy button for the `ERROR` session, so please update the PR. The destroy feature can also be triggered by the checkboxes in front of each session, so update `checkboxRenderer` as well in the same way.

2020-09-11 00:13 UTC, adrysn commented on src/components/backend-ai-session-list.ts
> +          ${(this._isRunning && !this._isPreparing(rowData.item.status)) ? html`
Good. We now do not need to support the legacy API (version < 5) in the main branch. But, the destroy button should be displayed for `ERROR` sessions to force-terminate them. So, please update the line like following:

```javascript
${(this._isRunning && !this._isPreparing(rowData.item.status)) || this._isError(rowData.item.status) ? html`
```

`_isError` function might look like:

```javascript
_isError(status) {
  return status === 'ERROR';
}
```

Good location for this function would be after `_isPreparing` function.

2020-09-14 12:55 UTC, inureyes approved these changes
LGTM

2020-09-14 12:58 UTC, merged