feat: add login block feature (#783)
lablup/backend.ai-console pull request #784
Opened 2020-11-15 09:04 UTC by inureyes

This PR resolves #783 (client solution)

2020-11-15 10:00 UTC, lizable reviewed
I guess the count of login attempt get initialized when the user clears localStorage explicitly and refreshes the page or the user uses "incognito" mode in a browser.
Those circumventing methods enables the user to login again and again.

How about adding a simple server-side DB table for counting login attempts to prevent those circumventing methods?

2020-11-15 16:16 UTC, adrysn requested changes
Wee need to reset `login_attempt` after successful login. Otherwise, after 5 consecutive successful login and logout will block the 6th normal login attempt.

2020-11-16 03:15 UTC, lizable approved these changes

2020-11-16 03:37 UTC, inureyes commented
@adrysn Fixed. Will merge now.

2020-11-16 03:38 UTC, merged