feat: add progress bar support for image rescan (#898)
lablup/backend.ai-console pull request #900
Opened 2021-02-01 06:47 UTC by mickowale

(#898)

2021-02-02 01:08 UTC, inureyes requested changes
@mickowale Please add comment to the methods. Other things looks fine (need more test / migrate into sidebar but it will be handled with another issue)

2021-02-02 01:08 UTC, inureyes commented on src/lib/backend.ai-client-node.js
> +    attach_background_task(task_id) {
@mickowale We need a comment section above this method. (It is referenced by TypeScript to check the parameter type)

2021-02-02 01:08 UTC, inureyes commented on src/lib/backend.ai-client-node.ts
> +  attach_background_task(task_id: string) {
@mickowale We need a comment section above this method. (It is referenced by TypeScript to check the parameter type)

2021-02-02 02:12 UTC, adrysn commented
There is also a rescan images in backend-ai-registry-list.ts to update individual registries. I think it needs to be updated as well.

2021-02-02 03:20 UTC, mickowale commented
> There is also a rescan images in backend-ai-registry-list.ts to update individual registries. I think it needs to be updated as well.

I have updated this now and also merged with the main branch. I will squash the commits if the current state is okay.

2021-02-03 00:26 UTC, inureyes approved these changes
LGTM.

2021-02-03 00:27 UTC, inureyes commented
@mickowale Good! I'll squash and merge into main branch. :D

2021-02-03 00:27 UTC, merged